# Generated by Django 4.0.4 on 2022-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
